# Generated by Django 3.2.4 on 2021-06-17 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.IntegerField()),
                ('quartos', models.IntegerField(blank=True)),
                ('banheiro', models.IntegerField(blank=True)),
                ('garagem', models.IntegerField(blank=True)),
                ('hectares', models.IntegerField(max_length=200)),
                ('tamanho_terreno', models.IntegerField()),
                ('foto_principal', models.ImageField(upload_to='photos/%d/%m/%Y/')),
                ('foto_1', models.ImageField(blank=True, upload_to='photos/%d/%m/%Y/')),
                ('foto_2', models.ImageField(blank=True, upload_to='photos/%d/%m/%Y/')),
                ('foto_3', models.ImageField(blank=True, upload_to='photos/%d/%m/%Y/')),
                ('foto_4', models.ImageField(blank=True, upload_to='photos/%d/%m/%Y/')),
                ('foto_5', models.ImageField(blank=True, upload_to='photos/%d/%m/%Y/')),
                ('foto_6', models.ImageField(blank=True, upload_to='photos/%d/%m/%Y/')),
                ('foto_7', models.ImageField(blank=True, upload_to='photos/%d/%m/%Y/')),
                ('publicado', models.BooleanField(default=True)),
                ('data_listada', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Listagen',
        ),
    ]
