# Generated by Django 3.2.4 on 2021-06-17 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0003_auto_20210616_2221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listagen',
            new_name='Listagem',
        ),
    ]
