# Generated by Django 3.2.4 on 2021-06-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0004_rename_listagen_listagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listagem',
            name='hectares',
            field=models.IntegerField(),
        ),
    ]
