# Generated by Django 3.2.4 on 2021-06-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0005_alter_listagem_hectares'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listagem',
            new_name='Listagen',
        ),
    ]
