# Generated by Django 3.2.4 on 2021-06-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0008_alter_listagen_corretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='listagen',
            name='tipo_de_imovel',
            field=models.CharField(blank=True, choices=[('URBANO', 'URBANO'), ('RURAL', 'RURAL')], max_length=100),
        ),
    ]
