# Generated by Django 3.2.4 on 2021-06-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0010_alter_listagen_tipo_de_imovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='listagen',
            name='foto_10',
            field=models.ImageField(blank=True, upload_to='photos/%d/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='listagen',
            name='foto_8',
            field=models.ImageField(blank=True, upload_to='photos/%d/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='listagen',
            name='foto_9',
            field=models.ImageField(blank=True, upload_to='photos/%d/%m/%Y/'),
        ),
    ]
