# Generated by Django 3.2.4 on 2021-06-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0011_auto_20210625_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listagen',
            name='quartos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
