# Generated by Django 3.2.4 on 2021-06-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0012_alter_listagen_quartos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listagen',
            name='banheiro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listagen',
            name='garagem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
