# Generated by Django 3.2.4 on 2021-07-04 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0005_alter_corretor_creci'),
        ('listagens', '0013_auto_20210628_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listagen',
            name='Corretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='corretor.corretor'),
        ),
    ]
