# Generated by Django 3.2.4 on 2021-07-07 14:44

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0014_alter_listagen_corretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='listagen',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
