# Generated by Django 3.2.4 on 2021-07-16 13:04

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0015_listagen_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listagen',
            old_name='video',
            new_name='video1',
        ),
        migrations.AddField(
            model_name='listagen',
            name='video2',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
