# Generated by Django 3.2.4 on 2021-08-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0018_alter_listagen_tipo_de_imovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listagen',
            name='tipo_de_imovel',
            field=models.CharField(choices=[('CASA', 'Casa'), ('CHÁCARA', 'Chácara'), ('FAZENDA', 'Fazenda'), ('LOTE', 'Lote'), ('SITIO', 'Sitio'), ('TERRENO', 'Terreno')], max_length=100),
        ),
    ]
