# Generated by Django 3.2.4 on 2021-08-11 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0005_alter_corretor_creci'),
        ('listagens', '0019_alter_listagen_tipo_de_imovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listagen',
            name='Corretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='corretor.corretor'),
        ),
        migrations.AlterField(
            model_name='listagen',
            name='tipo_de_imovel',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Chácara', 'Chácara'), ('Fazenda', 'Fazenda'), ('Lote', 'Lote'), ('Sítio', 'Sítio'), ('Terreno', 'Terreno')], max_length=100),
        ),
    ]
