# Generated by Django 3.2.4 on 2021-08-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listagens', '0020_auto_20210811_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listagen',
            old_name='tamanho_terreno',
            new_name='metrosquadrados',
        ),
    ]
