# Generated by Django 3.2.4 on 2021-06-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='photos/%d/%m/%Y')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
