# Generated by Django 3.2.4 on 2021-06-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='descricao',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
