# Generated by Django 3.2.4 on 2021-06-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0002_alter_corretor_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='telefone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
