# Generated by Django 3.2.4 on 2021-06-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0003_auto_20210621_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretor',
            name='creci',
            field=models.TextField(blank=True),
        ),
    ]
