# Generated by Django 3.2.4 on 2021-06-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0004_corretor_creci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='creci',
            field=models.CharField(max_length=100),
        ),
    ]
